### ISSUE TITLE
FT version 0.5.0 feature parity

### ISSUE THREAD

**Issue by Gumball2415** [Gumball2415/j0CC-FamiTracker#201]
Missing features not currently present in Dn-FT:
- [ ] NSF Playback Rate (#202)
- [ ] N163 automatic wave RAM allocation (#75)
- [ ] Frame editor pattern position indicator (#75)
- [ ] Nonlinear distortion for individial channels (#75)
- [ ] Group instruments (#75)
- [ ] DPCM state viewer (#75)
- [ ] Effect state viewer (#75)

**Comment by Gumball2415** [comment]
moved to https://github.com/orgs/Dn-Programming-Core-Management/projects/4
