### ISSUE TITLE
Feature: Appearance settings > Volume column color fade

### ISSUE THREAD

**Issue by eulyderg** [Gumball2415/j0CC-FamiTracker#284]
Feature request:
- Flag in appearance settings to fade volume column color based on the volume value
- Would add an additional color to the below selector for the volume column to fade to.
![image](https://github.com/Dn-Programming-Core-Management/Dn-FamiTracker/assets/31630195/cb1ce6e3-1678-4f84-8b6f-68b111a11080)

Implementation checklist:
- [ ] Color option to selector UI
- [ ] Checkbox to enable behavior
- [ ] Implement in theme export/import
- [ ] The behavior itself
